# This file was generated by GoReleaser. DO NOT EDIT.
class Keyfob < Formula
  desc "keyfob - a two-factor authentication agent suitable for AWS and Github"
  homepage "https://github.com/StevenACoffman/keyfob"
  version "0.3.0"

  if OS.mac?
    url "https://github.com/StevenACoffman/keyfob/releases/download/v0.3.0/keyfob_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "ee4451c02f590bbc21a0e1e4143cbea98f41821bf6c28366bb86af322aa4e968"
  elsif OS.linux?
    url "https://github.com/StevenACoffman/keyfob/releases/download/v0.3.0/keyfob_0.3.0_Linux_x86_64.tar.gz"
    sha256 "a40e2134be8f471a81c3053dc2cec2ca14585685ed8932c5eff2c408f9e6adaa"
  end

  def install
    bin.install "keyfob" => "keyfob"
    
    prefix.install_metafiles
  end

  test do
    system "#{bin}/keyfob", "--version"
  end
end
