# This file was generated by GoReleaser. DO NOT EDIT.
class Keyfob < Formula
  desc "A CLI for interacting with Tekton!"
  homepage "https://github.com/StevenACoffman/keyfob"
  version "0.2.0"

  if OS.mac?
    url "https://github.com/StevenACoffman/keyfob/releases/download/v0.2.0/keyfob_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "ae3b737fa2d114ec7753a5afc4bfab011a2cab3332e6beeb29fce38e380d240e"
  elsif OS.linux?
    url "https://github.com/StevenACoffman/keyfob/releases/download/v0.2.0/keyfob_0.2.0_Linux_x86_64.tar.gz"
    sha256 "451dc1ebb4c2f8a1dc5dbf4b623caafcf305e884fd89e8d7443905087e0d6ad5"
  end

  def install
    bin.install "keyfob" => "keyfob"

    prefix.install_metafiles
  end

  test do
    system "#{bin}/keyfob --version"
  end
end
